config/routes.rb
Musiclist::Application.routes.draw do
  get "show/index"
  resources :songs

  resources :albums

  root :to => redirect('/show/index')

end

app/models/album.rb
class Album < ActiveRecord::Base
  mount_uploader :albumCover, PictureUploader
  has_many :songs
  validates :artistName, :albumCover, :albumName, :genre, :presence => true
    	validates :artistName, :length => { :minimum => 2, :maximum => 50 }
    	validates :albumName, :length => { :minimum => 2, :maximum => 50  }
    	validates :albumName, :uniqueness => true  
      
      def self.search(search)
        if search
          where('artistName LIKE ?', "%#{search}%")
        else
          scoped
        end
      end
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :album
    	validates :songName, :presence => true
    	validates :songName, :length => { :minimum => 2, :maximum => 20 }

      def self.search(search)
        if search
          where('songName LIKE ?', "%#{search}%")
        else
          scoped
        end
      end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
   helper_method :sort_column, :sort_direction
  # GET /albums
  # GET /albums.json
  def index
     @albums = Album.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
     
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render action: 'show', status: :created, location: @album }
      else
        format.html { render action: 'new' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end

  private
  def sort_column
    Album.column_names.include?(params[:sort]) ? params[:sort] : "albumName"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:artistName, :albumCover, :albumName, :genre, :releaseDate)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/show_controller.rb
class ShowController < ApplicationController
  def index
    @albums = Album.all
     @songs = Song.all
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
 helper_method :sort_column, :sort_direction
  # GET /songs
  # GET /songs.json
  def index
     @songs = Song.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
  end
  def artistName
     
    end
  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render action: 'show', status: :created, location: @song }
      else
        format.html { render action: 'new' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end

  private
  def sort_column
    Song.column_names.include?(params[:sort]) ? params[:sort] : "songName"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:album_id, :songName, :songUrl)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  end
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :artistName %><br>
    <%= f.text_field :artistName %>
  </div>
  <div class="field">
    <%= f.label :albumCover %><br>
    <%= f.file_field :albumCover %>
  </div>
  <div class="field">
    <%= f.label :albumName %><br>
    <%= f.text_field :albumName %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :releaseDate %><br>
    <%= f.text_field :releaseDate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<div data-role="header">
<h1>Editing album</h1>

  <div data-role="navbar">
      <ul>
          <li><a href="/show/index" class="ui-btn-active">Home</a></li>
		  <li><a href="/jq">Jquery Data tables</a></li>
          <li><a href="/songs">Songs</a></li>
          <li><a href="/songs/new">New Songs</a></li>
          <li><a href="/albums">Artist</a></li>
          <li><a href="/albums/new">New Albums</a></li>
      </ul>
  </div><!-- /navbar -->
</div>
<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<div data-role="header">
  <h1>Listing albums</h1>
  <div data-role="navbar">
      <ul>
          <li><a href="/show/index" >Home</a></li>
		  <li><a href="/jq">Jquery Data tables</a></li>
          <li><a href="/songs">Songs</a></li>
          <li><a href="/songs/new">New Songs</a></li>
          <li class="ui-btn-active"><a href="/albums">Artist</a></li>
          <li><a href="/albums/new">New Albums</a></li>
      </ul>
  </div><!-- /navbar -->
</div>
<%= form_tag albums_path, :method => 'get' do %>
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
<ul data-role="listview">

    <li>
		<table>
			<tr>
	  <td style="width:27%"><%= sortable "albumCover_url" %></td>
      <td style="width:20%"><%= sortable "artistName" %></td>
      <td style="width:20%"><%= sortable "albumName" %></td>
      <td style="width:20%"><%= sortable "genre" %></td>
      <td style="width:20%"><%= sortable "releaseDate" %></td>
  </tr>
</table>
    </li>
  </ul>
<ul data-role="listview">

    <% @albums.each do |album| %>
      
		   <li>
	   		<table>
	   			<tr>
	   	  <td style="width:27%">  <%= image_tag(album.albumCover_url, :width => 100) if album.albumCover.present? %></td>
       <td style="width:20%"> <%= album.artistName %></td>
       <td style="width:20%"><%= album.albumName %></td>
       
        <td style="width:20%"><%= album.genre %></td>
        <td style="width:20%"><%= album.releaseDate %></td>
	</tr>
</table>
     </li>
       
    <% end %>
	<%= will_paginate @albums %>
	<br>
	<%= link_to 'New Album', new_album_path %>
    </ul>
   </div>
   

app/views/albums/new.html.erb
<div data-role="header">
 <h1>New album</h1>

  <div data-role="navbar">
      <ul>
          <li><a href="/show/index" >Home</a></li>
		  <li><a href="/jq">Jquery Data tables</a></li>
          <li><a href="/songs">Songs</a></li>
          <li><a href="/songs/new">New Songs</a></li>
          <li><a href="/albums">Artist</a></li>
          <li class="ui-btn-active"><a href="/albums/new">New Albums</a></li>
      </ul>
  </div><!-- /navbar -->
</div>
<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artistname:</strong>
  <%= @album.artistName %>
</p>

<p>
  <strong>Albumcover:</strong>
  <%= image_tag(@album.albumCover_url, :width => 200) if @album.albumCover.present? %>
</p>

<p>
  <strong>Albumname:</strong>
  <%= @album.albumName %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @album.genre %>
</p>

<p>
  <strong>Releasedate:</strong>
  <%= @album.releaseDate %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Musiclist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.3/jquery.mobile-1.4.3.min.css" />
  <script src="http://code.jquery.com/mobile/1.4.3/jquery.mobile-1.4.3.min.js"></script>
  
</head>
<body>
  <div data-role="page">
	  <div data-role="content">
    <%= yield %>
</div>
  </div>
</body>
</html>

app/views/show/index.html.erb
<div data-role="header">
  <h1>Listing songs</h1>
  <div data-role="navbar">
      <ul>
          <li><a href="/show/index" class="ui-btn-active">Home</a></li>
		  <li><a href="/jq">Jquery Data tables</a></li>
          <li><a href="/songs">Songs</a></li>
          <li><a href="/songs/new">New Songs</a></li>
          <li><a href="/albums">Artist</a></li>
          <li><a href="/albums/new">New Albums</a></li>
      </ul>
  </div><!-- /navbar -->
</div>

<%= form_tag songs_path, :method => 'get' do %>
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
<section id="song"></section>
<ul data-role="listview">

    <li>
		<table>
    <tr>
    <th>Album cover</th>
  <th>Artist name</th>
  <th>Album name</th>
  <th>Genre</th>
  <th>Releasedate</th>
  <th>album id</th>
  <th>Song Name</th>
  <th>play song</th>

    </tr>
</table>
</li>
</ul>
<ul data-role="listview">
   
      <% @songs.each do |song| %>
  	<li>
  		<table>
        <tr>
   		  
   	   	  <td style="width:20%">  <%= image_tag(song.album.albumCover_url, :width => 100) %></td>
          <td style="width:10%"> <%= song.album.artistName %></td>
          <td style="width:10%"><%= song.album.albumName %></td>
       
           <td style="width:10%"><%= song.album.genre %></td>
           <td style="width:10%"><%= song.album.releaseDate %></td>
           <td style="width:10%"><%= song.album_id %></td>
           <td style="width:10%"><%= song.songName %></td>
           <td style="width:10%"><%= link_to "Play", song.songUrl, :class => "play_song" %></td>
   	</tr>
   </table>
        </li>
        <% end %>

	  <br>
</ul>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :album_id %><br>
	<%= f.collection_select(:album_id, Album.all, :id, :albumName) %>
  </div>
  <div class="field">
    <%= f.label :songName %><br>
    <%= f.text_field :songName %>
  </div>
  <div class="field">
    <%= f.label :songUrl %><br>
    <%= f.text_field :songUrl %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<div data-role="header">
 <h1>Editing song</h1>

  <div data-role="navbar">
      <ul>
          <li><a href="/show/index" class="ui-btn-active">Home</a></li>
		  <li><a href="/jq">Jquery Data tables</a></li>
          <li><a href="/songs">Songs</a></li>
          <li><a href="/songs/new">New Songs</a></li>
          <li><a href="/albums">Artist</a></li>
          <li><a href="/albums/new">New Albums</a></li>
      </ul>
  </div><!-- /navbar -->
</div>
<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<div data-role="header">
  <h1>Listing songs</h1>

  <div data-role="navbar">
      <ul>
          <li><a href="/show/index" >Home</a></li>
		  <li><a href="/jq">Jquery Data tables</a></li>
          <li class="ui-btn-active"><a href="/songs">Songs</a></li>
          <li><a href="/songs/new">New Songs</a></li>
          <li><a href="/albums">Artist</a></li>
          <li><a href="/albums/new">New Albums</a></li>
      </ul>
  </div><!-- /navbar -->
</div>
<%= form_tag songs_path, :method => 'get' do %>
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
<section id="song"></section>
<ul data-role="listview">

    <li>
		<table>
    <tr>
	 <td style="width:33%"><%= sortable "album_id" %></td>
	 <td style="width:33%"><%= sortable "songName" %></td>
	 <td style="width:33%"><%= sortable "songUrl" %></td>
  
    </tr>
</table>
</li>
</ul>
<ul data-role="listview">
    <% @songs.each do |song| %>
	<li>
		<table>
      <tr>
		
        <td style="width:33%"><%= song.album_id %></td>
        <td style="width:33%"><%= song.songName %></td>
        <td style="width:33%"><%= link_to "Play", song.songUrl, :class => "play_song" %></td>
        
      </tr>
 
</table>
</li>
   <% end %>
</ul>
<%= will_paginate @songs %>
<br>
<script>
$(document).ready(function() {  
     var audioSection = $('section#song');  
     $('a.play_song').click(function() {  

     var audio = $('<audio>', {  
         controls : 'controls'  
     });  

     var url = $(this).attr('href');  
     $('<source>').attr('src', url).appendTo(audio);  
     audioSection.html(audio);  
     return false;       });  
 }); 
</script>
<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<div data-role="header">
 <h1>New song</h1>

  <div data-role="navbar">
      <ul>
          <li><a href="/show/index" >Home</a></li>
		  <li><a href="/jq">Jquery Data tables</a></li>
          <li><a href="/songs">Songs</a></li>
          <li class="ui-btn-active"><a href="/songs/new">New Songs</a></li>
          <li><a href="/albums">Artist</a></li>
          <li><a href="/albums/new">New Albums</a></li>
      </ul>
  </div><!-- /navbar -->
</div>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>
<section id="song">  
 </section>
<%= @song.artistName %>
<p>
  <strong>Album:</strong>
  <%= @song.album_id %>
</p>

<p>
  <strong>Songname:</strong>
  <%= @song.songName %>
</p>

<p>
  <strong>Songurl:</strong>
 <%= link_to "Play", @song.songUrl, :class => "play_song" %>
</p>
<script>
$(document).ready(function() {  
     var audioSection = $('section#song');  
     $('a.play_song').click(function() {  

     var audio = $('<audio>', {  
         controls : 'controls'  
     });  

     var url = $(this).attr('href');  
     $('<source>').attr('src', url).appendTo(audio);  
     audioSection.html(audio);  
     return false;       });  
 }); 
</script>
<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>